version: '2.1'

services:
  mysql:
    volumes:
      - /run/mysqld:/run/mysqld # make the socket available on the host

  # This runs once on #up
  # (it can potentially add the necessary user privileges and finish
  # see xwiki/mariaDB.socket-client.yml)
  # Some would name this service as a one-shot -task
  # but it is also useful as an interactive client.
  # To use interactively: docker-compose run --rm mysql_cli

  mysql_cli:
    depends_on:
    - mysql
    image: ${MYSQL_SERVER:-mysql:5.7}
    container_name: mariaDB_cli
    volumes:
    - /run/mysqld:/run/mysqld # access the socket on the host
     # a place to put the root password when it changes
    - ./official/mysql.cnf:/root/.my.cnf
    entrypoint:
    - mysql
    - --user=root
    # this is just the initial root password (obviously not-secure!)
    # it can be changed in the server which will disable this client
    # The new password can be placed in .my.cnf to re-enable this client
    - --password=mysql
    - --default-character-set=utf8
    - --init-command=GRANT ALL ON *.* TO `mysql`@`%`
