# This is docker's official php image
# This would be the most up to date and production ready.
# - but it may not have all of the extensions available out of the box

version: '3.1'

services:
  php_fpm:
    image: ${PHP_FPM_IMAGE:-php:fpm-alpine}
    environment:
      ANGEL: ${ANGEL}
    working_dir: /srv
    volumes:
    - ${PHP_FPM_VOLUMES_SRC:-./hub/official/php_fpm/src}:/srv:rw${MOUNT_OPTIONS}
    - ${PHP_FPM_VOLUMES_HTML:-./hub/official/php_fpm/html}:/var/www/html:rw${MOUNT_OPTIONS}

# OPTIONS
# PHP_FPM_IMAGE=php:fpm
# PHP_FPM_IMAGE=php:fpm-stretch
# PHP_FPM_IMAGE=php:7.3-fpm-stretch
# PHP_FPM_IMAGE=php:7.3-fpm-alpine
# PHP_FPM_IMAGE=php:7.3-fpm-alpine3.8
# PHP_FPM_IMAGE=php:7.2-fpm-stretch
# PHP_FPM_IMAGE=php:7.2-fpm-alpine
# PHP_FPM_IMAGE=php:7.2-fpm-alpine3.8
# PHP_FPM_IMAGE=php:7.1-fpm-stretch
# PHP_FPM_IMAGE=php:7.1-fpm-jessie
# PHP_FPM_IMAGE=php:7.1-fpm-alpine
# PHP_FPM_IMAGE=php:7.1-fpm-alpine3.8

#PHP_CLI_IMAGE=registry.gitlab.com/keithy/angelbox/php_mysql:alp3.9-php7.3-dev-swo4.3.1

