# This is docker's official php image
# This would be the most up to date and production ready.
# - but it may not have all of the extensions available out of the box

version: '3.1'

services:
  php_apache:
    image: ${PHP_APACHE_IMAGE:-php:apache}
    environment:
      ANGEL: ${ANGEL}
    working_dir: /srv
    volumes:
    - ${PHP_APACHE_VOLUMES_SRC:-./hub/official/php_apache/src}:/srv:rw${MOUNT_OPTIONS}
    - ${PHP_APACHE_VOLUMES_HTML:-./hub/official/php_apache/html}:/var/www/html:rw${MOUNT_OPTIONS}
    ports:
    - "${PHP_APACHE_PORTS_HTTP:-80}:80"

# OPTIONS
# PHP_APACHE_IMAGE=php:apache
# PHP_APACHE_IMAGE=php:7.3-apache-stretch
# PHP_APACHE_IMAGE=php:7.2-apache-stretch
# PHP_APACHE_IMAGE=php:7.1-apache-stretch
# PHP_APACHE_IMAGE=php:7.1-apache-jessie
# PHP_APACHE_IMAGE=registry.gitlab.com/keithy/angelbox/php:7-apache-mysqli

# Useful
#  dc up -d --force-recreate php_apache
#  dc exec php_apache bash
#  docker commit angelbox_php_apache_1 registry.gitlab.com/keithy/angelbox/php:7-apache-mysqli
#  docker push registry.gitlab.com/keithy/angelbox/php:7-apache-mysqli

