version: '3.1'

volumes:
  redis:
    driver: ${VOLUMES_DRIVER:-local}

services:
  redis:
    image: redis:alpine
    environment:
      ANGEL: ${ANGEL}
    command: >
      --appendonly ${REDIS_COMMAND_APPENDONLY:-yes}
    volumes:
    - redis:/data:rw${MOUNT_OPTIONS}
    restart: always

