version: '3.1'

volumes:
  redis:
    driver: ${VOLUMES_DRIVER:-local}

services:
  redis:
    image: redis:alpine
    environment:
      ANGEL: ${ANGEL}
      REDIS_PASSWORD: ${REDIS_ENVIRONMENT_REDIS_PASSWORD:-password}
    command: redis-server --appendonly yes
    volumes:
    - redis:/data:rw${MOUNT_OPTIONS}
    restart: always
