#!/bin/bash
# Run this preprocessor when the configuration changes to
# regenerate the .env file for docker-compose
# 
# 1) cd to the directory where your configuration files are.
# 2) Invoke the specific `docker-compose-use` that belongs to your Angelbox instance
#       you may have more than one!

set -ue

# Command
ANGELBOX_DIR=$(readlink -f "${BASH_SOURCE[0]%/*}")

# Argument $1 : The source *.env file (comments and blank lines allowed)
SERVICES="${1:-angelbox.env}"

# Argument $2 : A second source *.env file providing server specific environment values
VALUES="${2:-}"

# Argument $3 : a default server configuration file (obtained from the server itself)
SERVER_ENV_FILE="${3:-}"

# Environment variable allows alternative output file for testing
out="${DCU_OUT:-$ANGELBOX_DIR/.env}"

## Reset the output file
cp /dev/null ${out}
 
## Prepend servers own environment variables
if [ -f "${SERVER_ENV_FILE}" ]; then
	echo "######################################################################" >> ${out}
	echo "SERVER_FILE=$SERVER_ENV_FILE" > "${out}"
	cat "$SERVER_ENV_FILE" >> "${out}"
fi

## Process services definition file

echo "######################################################################" >> ${out}
echo "SERVICES_FILE=$SERVICES" >> "${out}"

# Temporary files
rand=$RANDOM
tmpA="/tmp/dcu-${rand}a"
tmpB="/tmp/dcu-${rand}b"
tmpC="/tmp/dcu-${rand}c"

# Step 1. Whitespace is trimmed
sed -E 's/^ *//;s/ *$//' "$SERVICES" > "$tmpA"

# Step 2. Lines with a single '#' are removed completely)
# This allows commenting to work within a series of \ separated lines
# not conventional, but more readable
## lines will survive this filter.

grep -vE "^#([^#]|$)" "$tmpA" > "$tmpB"

# Step 3. Remove Empty lines
grep . "$tmpB" > "$tmpA"

# Step 4. Lines ending in \ are concatenated
awk '{if (sub(/\\$/,"")) printf "%s", $0; else print $0}' "$tmpA" >> "${out}"

## Append additional environment variables

echo "######################################################################" >> ${out}
echo "PARAMETERS_FILE=$VALUES" >> "${out}"
cat "$VALUES" >> "${out}"
 
## Report success
	
echo "Set ${out}" 2>&1

## Tidy Up

rm /tmp/dcu-*
set +ue



