#!/bin/env bash
# Run this preprocessor when the configuration changes to
# regenerate the .env file for docker-compose
# 
# 1) cd to the directory where your configuration files are.
# 2) Invoke the specific `docker-compose-use` that belongs to your Angelbox instance
#       you may have more than one!

set -ue

# Environment Variable 
[[ ! -f "$SERVER_ENV_FILE" ]] && echo "$SERVER_ENV_FILE is missing" && exit

# Command
ANGELBOX_DIR=$(readlink -f "${BASH_SOURCE[0]%/*}")

# Argument $1 : The source *.env file (comments and blank lines allowed)

SERVICES="${1:-angelbox.env}"

# Argument $2 : A second source *.env file providing server specific environment values
VALUES="${2:-/etc/angelbox/server.env}"

# Argument $3 : The output file (default .env) - for testing
out="${3:-$ANGELBOX_DIR/.env}"

echo "######################################################################" >> ${out}
# Append servers OWN environment variables

echo "## From: $SERVER_ENV_FILE" > "${out}"
cat "$SERVER_ENV_FILE" >> "${out}"

echo "######################################################################" >> ${out}
# Process services definition file

echo "## From: $SERVICES" >> "${out}"

# Temporary files
rand=$RANDOM
tmpA="/tmp/dcu-${rand}a"
tmpB="/tmp/dcu-${rand}b"
tmpC="/tmp/dcu-${rand}c"

# Step 1. Whitespace is trimmed
sed -E 's/^ *//;s/ *$//' "$SERVICES" > "$tmpA"

# Step 2. Lines with a single '#' are removed completely)
# This allows commenting to work within a series of \ separated lines
# not conventional, but more readable
## lines will survive this filter.

grep -vE "^#([^#]|$)" "$tmpA" > "$tmpB"

# Step 4. Remove Empty lines
grep . "$tmpB" > "$tmpA"

# Step 3. Lines ending in \ are concatenated
awk '{if (sub(/\\$/,"")) printf "%s", $0; else print $0}' "$tmpA" >> "${out}"

echo "######################################################################" >> ${out}
# Append additional overriding environment variables

echo "## From: $VALUES" >> "${out}"
cat "$VALUES" >> "${out}"
 
echo "Set ${out}" 2>&1
