version: '3.1'

services:
  dnsmasq:
    image: ${IMAGE_DNSMASQ:-andyshinn/dnsmasq:2.78}
    environment:
      ANGEL: ${ANGEL}
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ${DNSMASQ_VOLUMES_CONF:-./hub/andyshinn/dnsmasq.conf}:/etc/dnsmasq.d/local.conf
    cap_add:
      - NET_ADMIN
    entrypoint:
      - dnsmasq
      - -k
      - --log-facility=-
