version: '3.1'

services:
  nginx:
    image: ${NGINX_IMAGE:-nginx:alpine}
    command: [nginx-debug, '-g', 'daemon off;'] # optional
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_VOLUMES_NGINX_CONF:-./openresty/nginx.conf}:/etc/nginx/nginx.conf
    restart: always

# OpenResty Options https://hub.docker.com/_/nginx

# $NGINX_IMAGE=nginx:alpine 
# $NGINX_IMAGE=nginx:alpine-perl
# $NGINX_IMAGE=nginx:latest
# $NGINX_IMAGE=nginx:stable 

