# Use local overriding file to add and integrate services
# The first time the database is run, defaults are used
# However if the passwords are changed, the new password can be placed in the
# credentials file, subsequent build of xwiki/client will pick up the new passwords
# (Note the mysql/password is set in the persistent volume hibernate.cfg.xml anyhow)

version: '3.1'

services:
  resty:
    # once built the image has this name
    image: "openresty:alpine-no-sse42"
    build:
      # remote definition
      context: "./keithy/openresty/build"
#     # context: "https://gitlab.com/keithy/docker-openresty.git#keithy:latest"
      # BUILDTIME ENVIRONMENT VARS
      args:
        BASE_image: alpine
    environment:
      ANGEL: ${ANGEL}
    environment:
      BASE_TAG: 3.8
    # RUNTIME ENVIRONMENT VARS
    # The DB_USER/DB_PASSWORD/DB_HOST variables are patched into hibernate.cfg.xml
    restart: always




