version: '3.1'

volumes:
  certificates:
    driver: ${VOLUMES_DRIVER:-local}

services:
  resty:
    image: ${RESTY_IMAGE:-valian/docker-nginx-auto-ssl}
    volumes:
    - ${RESTY_CERTIFICATES:-certificates}:/etc/resty-auto-ssl:rw${MOUNT_OPTIONS}
    environment:
      ALLOWED_DOMAINS: $RESTY_ENVIRONMENT_ALLOWED_DOMAINS
      SITES: $RESTY_ENVIRONMENT_SITES

# OTHER OPTIONS
#
# RESTY_IMAGE:-valian/docker-nginx-auto-ssl
# RESTY_IMAGE=registry.gitlab.com/keithy/angelbox/openresty-no-sse4.2_autossl:alpine-fat

