version: '3.1'

volumes:
  certificates:
    driver: ${VOLUMES_DRIVER:-local}

services:
  resty:
    image: ${RESTY_IMAGE_AUTOSSL:-valian/docker-nginx-auto-ssl}
    volumes:
    - ${RESTY_DIR_AUTOSSL:-./hub/openresty/openresty/+autossl}:/etc/autossl:ro
    - ${RESTY_VOLUME_CERTIFICATES:-certificates}:/etc/resty-auto-ssl:rw${MOUNT_OPTIONS}
    - ./hub/openresty/openresty/+autossl/challenge-response.http.conf:/etc/nginx/autossl-challenge-response.http.conf:ro
    - ./hub/openresty/openresty/+autossl/autossl_certs.https.conf:/etc/nginx/autossl_certs.https.conf:ro
    entrypoint:
    - /etc/autossl/entrypoint.sh
#    entrypoint: ["sh", "-c", "sleep 2073600"]
    environment:
      ALLOWED_DOMAINS: ${RESTY_ALLOWED_DOMAINS:-.*}
      SITES: ${RESTY_SITES:-}

# OPTIONS
#
# RESTY_IMAGE_AUTOSSL=valian/docker-nginx-auto-ssl
# RESTY_IMAGE_AUTOSSL=registry.gitlab.com/keithy/angelbox/openresty:alpine3.8-no-sse4.2-fat_autossl
# RESTY_IMAGE_AUTOSSL=registry.gitlab.com/keithy/angelbox/openresty:alpine3.8-no-sse4.2_autossl

#RESTY_ALLOWED_DOMAINS=serve.homeunix.com,test.serve.homeunix.com
#RESTY_SITES=serve.homeunix.com=php_fpm:9000,test.serve.homeunix.com=php_fpm2:9001
