version: '3.1'

volumes:
  certificates:
    driver: ${VOLUMES_DRIVER:-local}

services:
  resty:
    image: ${RESTY_IMAGE_AUTOSSL:-valian/docker-nginx-auto-ssl}
    volumes:
    - ${RESTY_VOLUMES_CERTIFICATES:-certificates}:/etc/resty-auto-ssl:rw${MOUNT_OPTIONS}
    entrypoint:
    - ./entrypoint_autossl.sh
    environment:
      ANGEL: ${ANGEL}
      ALLOWED_DOMAINS: ${RESTY_ENVIRONMENT_ALLOWED_DOMAINS:-.*}
      SITES: ${RESTY_ENVIRONMENT_SITES}
      FORCE_HTTPS: ${RESTY_ENVIRONMENT_FORCE_HTTPS:-true}

# OPTIONS
#
# RESTY_IMAGE_AUTOSSL=valian/docker-nginx-auto-ssl
# RESTY_IMAGE_AUTOSSL=registry.gitlab.com/keithy/angelbox/openresty:alpine3.8-no-sse4.2-fat_autossl
# RESTY_IMAGE_AUTOSSL=registry.gitlab.com/keithy/angelbox/openresty:alpine3.8-no-sse4.2_autossl

#RESTY_ENVIRONMENT_ALLOWED_DOMAINS=serve.homeunix.com,test.serve.homeunix.com
#RESTY_ENVIRONMENT_SITES=serve.homeunix.com=php_fpm:9000,test.serve.homeunix.com=php_fpm2:9001
