# This is php-fpm as pre-packaged in alpine packages
# This is convenient, well organised and fast to build
# It will not be as upto date as the docker php:alpine releases.

version: '2'

volumes:
  wp_bedrock:
     driver: anybox/buttervolume:latest # btrfs volume driver

services:
  phpfpm:
#   entrypoint: ["sh", "-c", "sleep 2073600"] # for debugging
    command: [ "php-fpm" ]
    image: alpine+phpfpm
    environment:
      ANGEL: ${ANGEL}
    build:
      context: ./php/alpine+phpfpm
      args:
        FROM: alpine:edge
        BUILD_ENV: /build/default.env
        BUILD_SCRIPT: /build/alpine-3.8+phpfpm.sh
        BUILD_CLEAN: "false"
        UID: 82
        USER: www-data
    expose:
      - "9000"
    depends_on:
      - mariaDB
      - memcached
#     - elasticsearch
    env_file:
      - /etc/wordpress_credentials.env
    environment:
      - WORDPRESS_DB_NAME=dev
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mariaDB
    volumes:
      - wp_bedrock:/var/www/html
#     - ../wp-docker-bedrock/config/php-fpm/php.ini:/usr/local/etc/php/php.ini
#     - ../wp-docker-bedrock/config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

#    extra_hosts:
#      - "wp-docker-bedrock.dev:172.18.0.1"
#    restart: always

