# This is openresty as pre-packaged in alpine packages
# This is convenient, well organised and fast to build

version: '3.1'

services:
  resty:
    entrypoint: ["sh", "-c", "sleep 2073600"] # for debugging
#   entrypoint: [ "/entrypoint.sh" ]
    command: [ ]
    image: keithy/openresty-no-sse4.2:alpine-fat 
    build: 
      context: ./keithy/openresty
      args:
        FROM: alpine:3.8
        BUILD_ENV: default.env
        BUILD_SCRIPT: build-alpine-fat.sh
        BUILD_CONFIG: config-no-sse4.2.sh
        UID: 83
        USER: resty
    expose:
      - 80
      - 443
    depends_on:
    env_file:
    environment:
    volumes:
      - ${RESTY_VOLUMES_NGINX_CONF_D:-}:/etc/nginx/conf.d
#   restart: always

