version: '3.1'

volumes:
  certificates:
    driver: ${VOLUMES_DRIVER:-local}

services:
  resty:
    image: ${RESTY_IMAGE:-valian/docker-nginx-auto-ssl}
    container_name: resty
    ports:
      - 80:80
      - 443:443
    volumes:
    - ${RESTY_CERTIFICATES:-certificates}:/etc/resty-auto-ssl:rw${MOUNT_OPTIONS}
    - ${RESTY_VOLUMES_NGINX_CONFDIR:-./openresty/nginx.d}:/etc/nginx/nginx.d:rw${MOUNT_OPTIONS}
    environment:
      ALLOWED_DOMAINS: $RESTY_ENVIRONMENT_ALLOWED_DOMAINS
      SITES: $RESTY_ENVIRONMENT_SITES
#    restart: unless-stopped

# OTHER OPTIONS FOUND
# a) https://github.com/Lomotif/openresty-docker
# $RESTY_IMAGE=lomotif/openresty
# $PRODUCTION=AUTO_SSL_PROD_CA=1
 
# b) https://github.com/Valian/docker-nginx-auto-ssl
# uses alpine-fat
# $RESTY_IMAGE=lomotif/openresty

# c)
# uses xenial
# $RESTY_IMAGE=

# $RESTY_CERTIFICATES=lets-certs
# $RESTY_CERTIFICATES=/usr/local/etc/certificates

