version: '3.1'

services:
  nginx:
    image: nginx:alpine
    command: [nginx-debug, '-g', 'daemon off;'] # optional
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

 

