version: '3.1'

services:
  resty:
    image: ${RESTY_IMAGE:-openresty:alpine-fat}
    command: [nginx-debug, '-g', 'daemon off;'] # optional
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${RESTY_VOLUMES_NGINX_CONF:-./openresty/nginx.conf}:/etc/nginx/nginx.conf
    restart: always

# OpenResty Options https://hub.docker.com/r/openresty/openresty/

# $RESTY_IMAGE=openresty:alpine 
# $RESTY_IMAGE=openresty:alpine-fat
# $RESTY_IMAGE=openresty:centos
# $RESTY_IMAGE=openresty:stretch 
# $RESTY_IMAGE=openresty:bionic
# $RESTY_IMAGE=openresty:xenial

