version: '3.1'

volumes:
  certificates:
    driver: ${VOLUMES_DRIVER:-local}

services:
  resty:
    image: ${RESTY_IMAGE:-valian/docker-nginx-auto-ssl}
    container_name: resty
    ports:
    - ${RESTY_PORTS_HTTP:-80}:80
    - ${RESTY_PORTS_HTTPS:-443}:443
    volumes:
    - ${RESTY_CERTIFICATES:-certificates}:/etc/resty-auto-ssl:rw${MOUNT_OPTIONS}
    - ${RESTY_VOLUMES_NGINX_CONF_D:-./openresty/nginx.d}:/etc/nginx/nginx.d:rw${MOUNT_OPTIONS}
    environment:
      ALLOWED_DOMAINS: $RESTY_ENVIRONMENT_ALLOWED_DOMAINS
      SITES: $RESTY_ENVIRONMENT_SITES
    restart: always

# OTHER OPTIONS
#
# $RESTY_IMAGE=registry.gitlab.com/keithy/angelbox/openresty-no-sse4.2_autossl:alpine-fat

