version: '3.1'

services:
  resty:
    image: ${RESTY_IMAGE:-openresty/openresty:alpine}
    volumes:
      - ${RESTY_DIR_ANGEL:-./hub/openresty/openresty/angel}:/etc/angel:ro
    entrypoint:
    - /etc/angel/entrypoint.sh
    ports:
    - "${RESTY_PORTS_HTTP:-80:80}"
    - "${RESTY_PORTS_HTTPS:-443:443}"
    environment:
      ANGEL: ${ANGEL}
      WORKER_PROCESSES: ${RESTY_WORKER_PROCESSES:-2}

# restart: always

# OpenResty Options https://hub.docker.com/r/openresty/openresty/

# $RESTY_IMAGE=openresty:alpine
# $RESTY_IMAGE=openresty:alpine-fat
# $RESTY_IMAGE=openresty:centos
# $RESTY_IMAGE=openresty:stretch
# $RESTY_IMAGE=openresty:bionic
# $RESTY_IMAGE=openresty:xenial

# $RESTY_IMAGE=registry.gitlab.com/keithy/angelbox/openresty-no-sse4.2:alpine
# $RESTY_IMAGE=registry.gitlab.com/keithy/angelbox/openresty-no-sse4.2:alpine-fat
