version: '3.1'

services:
  mysql_cli:
    depends_on:
    - mysql
    image: ${MYSQL_IMAGE:-mysql:5.7}
    environment:
      ANGEL: ${ANGEL}
    volumes:
    # data directory includes the socket
    - ${MYSQL_VOLUMES_DATADIR:-db}:/var/lib/mysql:rw${MOUNT_OPTIONS}
    - ${MYSQL_VOLUMES_DUMPS:-./hub/official/mysql/dumps}:/srv
    entrypoint:
    - mysql
    - --defaults-extra-file=/run/secrets/mysql_root_pass.cnf
    - --user=root
    - --socket=/var/lib/mysql/mysqld.sock
    - --default-character-set=utf8
    - --prompt=\u@\h [\d]>
    - --init-command=${MYSQL_CLI_ENTRYPOINT_INIT_COMMAND:-DO 1}
